# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        MainWindow.setStyleSheet("background-color:#212121;")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 50))
        self.label_3.setMaximumSize(QtCore.QSize(150, 50))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-weight: 700;  \n"
"    padding-left: 30px; \n"
"    color:#fd4a24      \n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.lineEdit_login = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_login.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_login.setStyleSheet(" border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding-left:6px;\n"
"color:#fff     ")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.lineEdit_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_senha.setStyleSheet(" border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding-left:6px;\n"
"color:#fff     ")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout.addWidget(self.lineEdit_senha)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet(" border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"color:#fff     ")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(100000, 20))
        self.label.setStyleSheet("color:#fd4a24; background-color:transparent;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(45)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonSE = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonSE.setMinimumSize(QtCore.QSize(75, 40))
        self.radioButtonSE.setMaximumSize(QtCore.QSize(75, 40))
        self.radioButtonSE.setTabletTracking(False)
        self.radioButtonSE.setStyleSheet("color:#fff;\n"
"border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding: 10px;\n"
"\n"
"")
        self.radioButtonSE.setObjectName("radioButtonSE")
        self.horizontalLayout_2.addWidget(self.radioButtonSE)
        self.radioButtonMA = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonMA.setMinimumSize(QtCore.QSize(75, 40))
        self.radioButtonMA.setMaximumSize(QtCore.QSize(75, 40))
        self.radioButtonMA.setStyleSheet("border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding: 10px;\n"
"color:#fff;")
        self.radioButtonMA.setObjectName("radioButtonMA")
        self.horizontalLayout_2.addWidget(self.radioButtonMA)
        self.radioButtonCE = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonCE.setMinimumSize(QtCore.QSize(75, 40))
        self.radioButtonCE.setMaximumSize(QtCore.QSize(75, 40))
        self.radioButtonCE.setStyleSheet("border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding: 10px;\n"
"color:#fff;")
        self.radioButtonCE.setObjectName("radioButtonCE")
        self.horizontalLayout_2.addWidget(self.radioButtonCE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit.setStyleSheet(" border: 1px solid #fd4a24;\n"
"border-radius:10px;\n"
"padding-left:6px;\n"
"color:#fff     ")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_cadastrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cadastrar.setEnabled(False)
        self.pushButton_cadastrar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_cadastrar.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(\n"
"        spread: pad, x1: 0, y1: 0.5, x2: 1, y2: 0.5,\n"
"        stop: 0 rgba(253, 74, 36, 1),\n"
"        stop: 0.44 rgba(255, 126, 0, 1),\n"
"        stop: 1 rgba(225, 73, 0, 1)\n"
"    );\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(\n"
"        spread: pad, x1: 0, y1: 0.5, x2: 1, y2: 0.5,\n"
"        stop: 0 rgba(253, 84, 46, 1),\n"
"        stop: 0.44 rgba(255, 136, 10, 1),\n"
"        stop: 1 rgba(235, 83, 10, 1)\n"
"    );\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(\n"
"        spread: pad, x1: 0, y1: 0.5, x2: 1, y2: 0.5,\n"
"        stop: 0 rgba(243, 64, 26, 1),\n"
"        stop: 0.44 rgba(245, 116, 0, 1),\n"
"        stop: 1 rgba(215, 63, 0, 1)\n"
"    );\n"
"}\n"
"")
        self.pushButton_cadastrar.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.verticalLayout.addWidget(self.pushButton_cadastrar)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AUTO ART/CRF"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "AUTO ART v2.0"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "LOGIN"))
        self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "SENHA"))
        self.pushButton.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.label.setText(_translate("MainWindow", "..."))
        self.radioButtonSE.setText(_translate("MainWindow", "CFT"))
        self.radioButtonMA.setText(_translate("MainWindow", "MA"))
        self.radioButtonCE.setText(_translate("MainWindow", "CE"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Número da ART"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "CADASTRAR"))
